export const ADOBE_EXCHANGE_HOME = "https://exchange.adobe.com/";

export const ADOBE_EXCHANGE_BATCHCROP_URL =
	process.env.NEXT_PUBLIC_ADOBE_EXCHANGE_BATCHCROP_URL || ADOBE_EXCHANGE_HOME;

export const ADOBE_EXCHANGE_EXPORT_EVERY_X_URL =
	process.env.NEXT_PUBLIC_ADOBE_EXCHANGE_EXPORT_EVERY_X_URL ||
	process.env.NEXT_PUBLIC_ADOBE_EXCHANGE_SLICE_EVERY_X_URL ||
	ADOBE_EXCHANGE_HOME;
